# print("hello world")    
# a = input("enter a value: ")
# print(type(a))
# name = "hiranmay"
# print(name[0:4])
# name = input("enter the name: ")
# print(name.count("a"))
# print(name.capitalize())
# print(name.upper())
# print(name.lower())
# print(name.find("y"))
# name = input("Enter your name: ")
# print("hello",name)
# marks=[45,23,49,46]
# print(marks)
# marks.append(56)
# print(marks)
# marks.insert(2,48)
# print(marks)
